name: Build.DockerImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nlucansk/python-terraform-cdk:$(date +%s)
        docker push nlucansk/python-terraform-cdk:$(date +%s)
